In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5, 4)
print(x)

tensor([[-7.6401e-33,  4.5574e-41, -7.6401e-33,  4.5574e-41],
        [-1.2997e-12,  4.5573e-41, -4.8219e-33,  4.5574e-41],
        [ 1.0913e+35,  4.5574e-41,  1.8636e+34,  4.5574e-41],
        [-4.7135e-33,  4.5574e-41, -1.2766e-12,  4.5573e-41],
        [ 1.8633e+34,  4.5574e-41, -1.2988e-12,  4.5573e-41]])


In [3]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.rand(5, 6)

tensor([[0.6979, 0.5742, 0.7253, 0.5097, 0.8824, 0.0689],
        [0.9562, 0.1246, 0.2158, 0.2691, 0.1251, 0.9167],
        [0.5237, 0.1637, 0.9983, 0.7733, 0.5676, 0.3815],
        [0.9595, 0.5809, 0.9759, 0.5240, 0.7665, 0.3648],
        [0.4969, 0.9597, 0.3422, 0.6551, 0.7556, 0.5877]])

In [5]:
torch.randn(5, 6)

tensor([[-0.2237,  1.3516, -0.3148, -1.1044,  0.4037,  1.5695],
        [ 0.6832,  0.6701,  0.9253, -0.5445, -0.7099, -0.3802],
        [-1.3727, -0.4868,  0.2510,  0.9592, -0.6936, -0.4240],
        [ 1.7792, -0.1610, -1.1361, -0.9438, -0.5653, -1.0645],
        [-1.7353, -0.5098, -0.6490,  0.7786,  1.9575, -0.3181]])

In [6]:
l = [13, 4]
r = np.array([4, 56, 7])

In [7]:
torch.tensor(l)

tensor([13,  4])

In [8]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [9]:
x.size()

torch.Size([5, 4])

In [11]:
type(x)

torch.Tensor

In [12]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.6263, 0.9511],
        [0.2967, 0.2145]])
tensor([[0.2824, 0.3948],
        [0.4182, 0.9298]])


In [13]:
x + y

tensor([[0.9087, 1.3459],
        [0.7149, 1.1443]])

In [14]:
torch.add(x, y)

tensor([[0.9087, 1.3459],
        [0.7149, 1.1443]])

In [15]:
y.add(x)

tensor([[0.9087, 1.3459],
        [0.7149, 1.1443]])

In [16]:
y.add_(x) # inplace 방식 - 더한 방식으로 바뀜, 변수를 대체하고자할 떄

tensor([[0.9087, 1.3459],
        [0.7149, 1.1443]])

In [17]:
y[1, 1]

tensor(1.1443)

In [18]:
y[:, 1]

tensor([1.3459, 1.1443])

In [19]:
x = torch.rand(8, 8)
print(x)

tensor([[0.7307, 0.3263, 0.3748, 0.1233, 0.1691, 0.3566, 0.8986, 0.6683],
        [0.2762, 0.3156, 0.9322, 0.1447, 0.2532, 0.4110, 0.9145, 0.1226],
        [0.5861, 0.7769, 0.5350, 0.4230, 0.2974, 0.9457, 0.6603, 0.5094],
        [0.1212, 0.2472, 0.5964, 0.0937, 0.6956, 0.8940, 0.8868, 0.0165],
        [0.0166, 0.1811, 0.9798, 0.5833, 0.3552, 0.9122, 0.3995, 0.4775],
        [0.9473, 0.8911, 0.3271, 0.8919, 0.3708, 0.0633, 0.5819, 0.4135],
        [0.4137, 0.7019, 0.6111, 0.9533, 0.6681, 0.3501, 0.1496, 0.9614],
        [0.1624, 0.5841, 0.1245, 0.2265, 0.3050, 0.3660, 0.8922, 0.1993]])


In [20]:
x.view(64)

tensor([0.7307, 0.3263, 0.3748, 0.1233, 0.1691, 0.3566, 0.8986, 0.6683, 0.2762,
        0.3156, 0.9322, 0.1447, 0.2532, 0.4110, 0.9145, 0.1226, 0.5861, 0.7769,
        0.5350, 0.4230, 0.2974, 0.9457, 0.6603, 0.5094, 0.1212, 0.2472, 0.5964,
        0.0937, 0.6956, 0.8940, 0.8868, 0.0165, 0.0166, 0.1811, 0.9798, 0.5833,
        0.3552, 0.9122, 0.3995, 0.4775, 0.9473, 0.8911, 0.3271, 0.8919, 0.3708,
        0.0633, 0.5819, 0.4135, 0.4137, 0.7019, 0.6111, 0.9533, 0.6681, 0.3501,
        0.1496, 0.9614, 0.1624, 0.5841, 0.1245, 0.2265, 0.3050, 0.3660, 0.8922,
        0.1993])

In [21]:
x.view(4, 16)

tensor([[0.7307, 0.3263, 0.3748, 0.1233, 0.1691, 0.3566, 0.8986, 0.6683, 0.2762,
         0.3156, 0.9322, 0.1447, 0.2532, 0.4110, 0.9145, 0.1226],
        [0.5861, 0.7769, 0.5350, 0.4230, 0.2974, 0.9457, 0.6603, 0.5094, 0.1212,
         0.2472, 0.5964, 0.0937, 0.6956, 0.8940, 0.8868, 0.0165],
        [0.0166, 0.1811, 0.9798, 0.5833, 0.3552, 0.9122, 0.3995, 0.4775, 0.9473,
         0.8911, 0.3271, 0.8919, 0.3708, 0.0633, 0.5819, 0.4135],
        [0.4137, 0.7019, 0.6111, 0.9533, 0.6681, 0.3501, 0.1496, 0.9614, 0.1624,
         0.5841, 0.1245, 0.2265, 0.3050, 0.3660, 0.8922, 0.1993]])

In [22]:
x.view(-1, 16)

tensor([[0.7307, 0.3263, 0.3748, 0.1233, 0.1691, 0.3566, 0.8986, 0.6683, 0.2762,
         0.3156, 0.9322, 0.1447, 0.2532, 0.4110, 0.9145, 0.1226],
        [0.5861, 0.7769, 0.5350, 0.4230, 0.2974, 0.9457, 0.6603, 0.5094, 0.1212,
         0.2472, 0.5964, 0.0937, 0.6956, 0.8940, 0.8868, 0.0165],
        [0.0166, 0.1811, 0.9798, 0.5833, 0.3552, 0.9122, 0.3995, 0.4775, 0.9473,
         0.8911, 0.3271, 0.8919, 0.3708, 0.0633, 0.5819, 0.4135],
        [0.4137, 0.7019, 0.6111, 0.9533, 0.6681, 0.3501, 0.1496, 0.9614, 0.1624,
         0.5841, 0.1245, 0.2265, 0.3050, 0.3660, 0.8922, 0.1993]])

In [23]:
x.view(-1, 4, 4)

tensor([[[0.7307, 0.3263, 0.3748, 0.1233],
         [0.1691, 0.3566, 0.8986, 0.6683],
         [0.2762, 0.3156, 0.9322, 0.1447],
         [0.2532, 0.4110, 0.9145, 0.1226]],

        [[0.5861, 0.7769, 0.5350, 0.4230],
         [0.2974, 0.9457, 0.6603, 0.5094],
         [0.1212, 0.2472, 0.5964, 0.0937],
         [0.6956, 0.8940, 0.8868, 0.0165]],

        [[0.0166, 0.1811, 0.9798, 0.5833],
         [0.3552, 0.9122, 0.3995, 0.4775],
         [0.9473, 0.8911, 0.3271, 0.8919],
         [0.3708, 0.0633, 0.5819, 0.4135]],

        [[0.4137, 0.7019, 0.6111, 0.9533],
         [0.6681, 0.3501, 0.1496, 0.9614],
         [0.1624, 0.5841, 0.1245, 0.2265],
         [0.3050, 0.3660, 0.8922, 0.1993]]])

In [24]:
y = x.numpy()
print(y)
type(y)

[[0.7306644  0.3263048  0.37484485 0.12329376 0.1691044  0.3566022
  0.89862365 0.66833764]
 [0.27620798 0.31559128 0.9322272  0.14465421 0.25321114 0.41103894
  0.9145273  0.12262887]
 [0.5861342  0.7769108  0.53501326 0.42295486 0.29735696 0.94574475
  0.66032434 0.5093519 ]
 [0.1212191  0.24716479 0.5963811  0.09366643 0.69557154 0.8940242
  0.8868329  0.01645166]
 [0.01664162 0.18110114 0.979824   0.5833042  0.35516346 0.91222364
  0.39954907 0.4775052 ]
 [0.9473328  0.89111686 0.32708657 0.8918534  0.37083018 0.06333244
  0.5818946  0.41345346]
 [0.4137168  0.70186317 0.61105853 0.9532844  0.6681058  0.35007697
  0.14957976 0.9613899 ]
 [0.1624409  0.58408755 0.12446845 0.22645277 0.30496305 0.36604702
  0.89221895 0.19930387]]


numpy.ndarray

In [29]:
# item : 텐서가 scalar일 때만 사용가능 - 정수나 숫자형태로 사용하고 싶을 때
# loss값을 사용하고 싶을 때
x = torch.ones(1)
print(x)
print(x.item())
print(int(x[0]))

tensor([1.])
1.0
1
