In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True) # x에 대해 역전파를 구하기 위해 즉, 미분하기 위해 모든 기록들을 저장

In [3]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [5]:
z = 2*y**2
res = z.mean()
print(z)

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)


In [6]:
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [7]:
# d(res) / dx_i = x_i + 1
# res = (z_1 + z_2 + z_3 + z_4) / 4
# z_i = 2 y_i ** 2
# z_i = 2(x_i + 1)**2

res.backward()

In [8]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [9]:
import torch.nn as nn
import torch.nn.functional as F # conv, linear, ... 다 이미 만들어져 있는 library - 위의 내용은 이렇게 흘러간다.